name: Update Citations Count

on:
  schedule:
    - cron: '0 0 * * 0'  # This runs the action every Sunday at midnight
  workflow_dispatch:  # This allows for manual triggering

jobs:
  update_citations:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js environment
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install requests beautifulsoup4

    - name: Run script to update citation count
      run: python update_citations.py

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update citation count" || echo "No changes to commit"
        git push
